# Example configuration with wandb enabled
# Copy this to your config file and modify as needed

# Enable wandb logging
WANDB:
  ENABLED: True
  PROJECT_NAME: "cbml-cub-experiment"  # Your project name
  ENTITY: "your-username"  # Your wandb username or team name
  WATCH_MODEL: True  # Watch model gradients

# Model configuration
MODEL:
  DEVICE: "cuda"
  BACKBONE:
    NAME: "resnet50"
  PRETRAIN: 'imagenet'
  HEAD:
    NAME: "linear_norm"
    DIM: 512

# Loss configuration
LOSSES:
  NAME: 'cbml_loss'
  NAME_AUX: ''
  AUX_WEIGHT: 0.01

# Data configuration
DATA:
  TRAIN_IMG_SOURCE: 'resource/datasets/CUB_200_2011/train.txt'
  TEST_IMG_SOURCE: 'resource/datasets/CUB_200_2011/test.txt'
  TRAIN_BATCHSIZE: 60
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 5
  KNN: 1

# Solver configuration
SOLVER:
  MAX_ITERS: 4000
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  CHECKPOINT_PERIOD: 200

# Save directory
SAVE_DIR: 'output/cub_resnet50_wandb'

# Validation
VALIDATION:
  VERBOSE: 200
  IS_VALIDATION: True 