MODEL:
  BACKBONE:
    NAME: resnet50
  PRETRAIN: output-resnet50-cub/model_005000.pth

SAVE_DIR: output-resnet50-cub

INPUT:
   MODE: 'RGB'
   PIXEL_MEAN: [0.485, 0.456, 0.406]
   PIXEL_STD: [0.229, 0.224, 0.225]

SOLVER:
  MAX_ITERS: 5000
  STEPS: [1200]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

LOSSES:
  CBML_LOSS:
    POS_A: 0.5
    POS_B: 0.5
    NEG_A: 1.0
    NEG_B: 0.01
    MARGIN: 0.1
    HYPER_WEIGHT: 0.2

DATA:
  TRAIN_IMG_SOURCE: resource/datasets/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: resource/datasets/CUB_200_2011/test.txt
  TRAIN_BATCHSIZE: 120
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 8

VALIDATION:
  VERBOSE: 200
